version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cinema-db
    networks:
      - cinema-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema-db"]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cinema-app-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - cinema-app-network
    ports:
      - 9090:9090

volumes:
  pgdata:
  pgadmin_data:
  prometheus_data:

networks:
  cinema-app-network:
    driver: bridge

